version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Build build
          command: docker build -t $DOCKER_USER/prabeshimage:$VERSION --build-arg version=$VERSION .
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker push prabeshimage image
          command: docker push $DOCKER_USER/prabeshimage

  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      -run:
         name: run deploy.sh
         command: ./deploy.sh
    

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build 
      - deploy:
          requires:
            - build